### ISSUE TITLE
Colored Diff

### ISSUE THREAD

**Issue by meshkin** [amouat/diffxml#2]
Hi,
As you know, the diff applications and utilities (such as netbeans, git and github) present diffs (insert, delete, ...) as colored parts. how can we have this feature in this module?
thanks

**Comment by amouat** [comment]
I don't really understand what you're asking for - you know the output is raw XML, right?

**Comment by amouat** [comment]
I'm closing this - I think the request is really for a GUI, which should probably be a separate project.
